"""iebiball.py - An implementation of the IEBIBALL system utility for z/OS."""

import unittest

from ..core import *
from .console import *

class IEBIBALL(RSECT):
  """
  https://www.etsy.com/listing/1535332741/iebiball-black-glossy-mug
  """
  WTO('Message 1')
  WTO('Message 2')
  WTO('Message 3')

  def __init__(self, messages=[]):
    """
    Initialize an instance of IEBIBALL.
    """
    self.messages = messages

class Tests(unittest.TestCase):
  """
  Test the IEBIBALL program.
  """
  messages = [
    # 24 July, 2024 - 12:18pm CDT
    ":wave:",
    "Nothing.",
    "I was going to complain about some behavior on this discord "
    "server that I perceived as toxic, but I'm probably just overly "
    "sensitive. I really despise the mainframe community sometimes.",
    "I'm not even complaining about the one message, it was the "
    "\"I'm an expert and I know everything and I'm not going to explain "
    "it to you unless you ask the right questions\" attitude.",
    # 4 November, 2024 - 3:15pm CST
    "Hey, are you still looking for volunteers to help moderate "
    "the SZE server? Just wanted to express my interest.",
    "My experience is that I used to be a wikipedia administrator",
    "Lol",
    "Sick",
    ":sweat:",
    "Get well soon!!",
    "I had an awesome time at re:ipl",
    "Like it was honestly the highlight of going to share",
    ":smiling_face_with_3_hearts",
    # 7 January, 2025 - 1:41pm CST
    "I keep thinking someone posted porn in the zos channel lmfao",
    "we??",
    "crowdsourced discord administration",
    "put it in a wow game",
    "brann your task is to administer this server",
    '"no"',
    "I haven't played since cata",
    "I'd love to play vanilla again",
    "I loved getting destroyed by deathwing in random zones",
    "Oh  man, it's been ages. I can't remember, honestly. I raided "
    "in WOTLK but only a little bit in cata.",
    "damn! you lasted a lot longer than me",
    "I ended up switching from WoW to FF14 shortly after college "
    "and that became my main mmo for a long time",
    "then I had kids",
    "that's incredible!!",
    "so you have experience leading online communities",
    "I really admire that",
    "I'm glad you recognized that",
    "All",
    "Human warrior was main",
    "Alliance",
    "so lame",
    "haha",
    "I tanked",
    "Mine was Redcap with an umlaut on the a",
    "I really loved playing resto druid",
    "And an alteration(?) shman named Roxanne",
    "i wonder she's doing now",
    "I got locked out of my account and I've been putting off recovering "
    "for years",
    "Probably will end up creating a new one if I ever get back into it",
    "how big is your screenshot folder?",
    "BRO",
    "Let me see if I can find my characters",
    "I played on <redacted> mainly",
    # 7 January, 2025 - 1:57pm CST
    "Nothin and I gotta get ready for an interview lol",
    "Not for a job",
    "Thank the gods",
    "It's a new CS student and they want to talk to me about what it's like beign (sic) a software engineer",
    "what should I say?",
    "That's wonderful",
    "I was just gonna tell him to run",
    # 7 January, 2025 - 10:12pm CST
    "Okay hear me out",
    "Let's create a crowdsourced mainframe ISV",
    "Like",
    "Okay this idea might not be fully formed in my brain",
    "Lmfao I'm so aorry",
    "Okay so we would be q (sic) company with a public Github organization",
    "And people from around the world could contribute code to the organization",
    "Think Uber but programming",
    "Hell yeah",
    "Wide open baby",
    "But somehow we need to pay people who contribute code",
    "And maybe we could find an algorithm to rate people's code",
    "And people could compete to create the best code",
    "Like best sort algorithm gets paid 1 cent every time it executes",
    "But holy shit someone found a better sorting algorithm",
    "Now they're getting that cent",
    "We are all reinventing the wheel together.",
    "Anyway the ISV just coordinates all this",
    "It's mainframe software but I guess it doesn't have to be",
    # 7 January, 2025 - 10:19pm CST
    "Right",
    "Like how do we fairly pay people to reinvent the wheel all the time",
    "That's what I'm trying to solve",
    "But also eventually maybe we'll arrive at the \"best solutions\" and they will all be in one place",
    "And then we can all be done programming.",
    "Like why are we still writing new software? All the fucking time",
    "It needs to end",
    ":joy:",
    "Thanks for coming to my TED talk.",
    "...",
    "Halting problem",
    "I think I'm trying to find an algorithm to rate code",
    "Probably lol",
    "People always find ways to abuse human systems.",
    "Or like"
    # 7 January, 2025 - 10:27pm CST
    "Injecting code that does crypto mining in someone else's code in a sneaky way to sabotage them",
    "Lol",
    "Idk I guess the company oversees that people are behaving",
    "Or it could be completely community driven",
    "For sure.",
    "Somehow wikipedia manages to filter out all the bs. A lot of it is automated now.",
    # 7 January, 2025 - 10:36pm CST
    "Yeah...",
    "Lordy lordy",
    "My office mate from IBM and I talk about this all the time",
    "Yeah",
    # 7 January, 2025 - 10:43pm CST
    "See this is where I start having a moral dilemma",
    "I'd love to just start creating a shit ton of conversion tools and letting these big ass shitty corporations profit off the fruits of my labor",
    "But I can't",
    "The companies need to die",
    "So is the ultimate goal to just get everyone off z?",
    "Me too.",
    # 7 January, 2025 - 10:51pm CST
    "I'm so fucking sick of it.",
    "Hahaha",
    "I'm a pariah by choice.",
    "good.",
    "High school never ends.",
    "My job just feels like kindergaten most days lol.",
    "I am ready right now.",
    "I tried forming a union at IBM.",
    "I went on strike for two weeks.",
    "To summarize my position: I don't think bringing open source to z is the answer because ultimately it benefits the companies.",
    "The answer is to bring z to the rest of the world",
    # 7 January, 2025 - 10:58pm CST
    "And then people will realize how unnecessary it is.",
    "Like z/OS needs to be open source.",
    "That's what I think.",
    "If they can't do that then I'm going to build z/NickOS in the public domain and find a way to transfer z/OS shit to z/NickOS",
    "That's my strategy.",
    "I would sell the migrations for 1 million a pop.",
    "I need to feed my kids man.",
    "Yeah. would have to start migrating small companies and build up our expertise. But we could streamline it.",
    "Ceos would drool at the thought of migrating off z for such a low price. especially if we can successfully do it.",
    "You know how JES2 was originally a field developed product?",
    "It's the key to the kingdom",
    "I'd start by shipping my own replacement for JES2.",
    "Provide metrics to show how much better mine is",
    "Go from there idk",
    # 7 January, 2025 - 11:06pm CST
    "They desperately want off the platform.",
    "We all know this.",
    "Total bs.",
    "Does not exist.",
    "Lol no I'll check it out",
    # 7 January, 2025 - 11:20pm CST
    "See this is why I need to write an article about the lack of a skills gap.",
    "Nobody gets it.",
    "I'm sorry.",
    "The mainframe is cool.",
    "That's why I, a young person, work on it.",
    "Not if we agree to compete with them.",
    "It could be amazing for our careers.",
    "Be a pariah with me.",
    # 7 January, 2025 - 11:52pm CST
    "Thanks! Honestly just having someone to talk to about this kind of stuff is really helpful.",
    "Let me know if it's ever too much or if I'm causing too much noise in the server.",
    "And don't make me a mod.",
    "I'm way too impulsive.",
    "Right, the server.",
    "Balance me out my duuuude",
    "I'm glad you enjoyed it!",
    "And yes, let's change the world.",
    "Okay!",
    # 7 January, 2025 - 11:59pm CST
    "I'll have to tell you about how I destroyed my chances of ever writing for planet mainframe lol",
    "Nah this was share kc timeframe when I was job hunting. They were in the process of taking over the tuning letter from Cheryl Watson and they were looking for a writer lol",
    "They wanted me to write an article about a performance related topic",
    "And I put it off all summer and kept telling them I was going to knock it out",
    "Then put (sic) of the blue I said I didn't have what it took to be a writer for the tuning letter",
    "And I ran into the guy who interviewed me at share and he asked me what happened",
    "I told him I was dealing with a lot of personal shit",
    "I actually don't know if they found a writer for it yet",
    "But I was thinking of using it to talk about some of my gripes with the platform / industry",
    "Its not performance",
    "It's cost optimization",
    "Well I mean it's a little bit of both",
    "I think the thought of making every transaction 0.001 cent cheaper is more appealing to people running z",
    # 8 January, 2025 - 12:06am CST
    "I've read a couple issues",
    "I think streaming is the future",
    "I mentioned that to planet mainframe and I'm worried they might steal my idea lol",
    "I think streaming is how to get people interested in mainframes",
    "Show them the technology and how to do stuff with it",
    "Be a character",
    "Yeah",
    "That would have been a pretty cool job but I'm a programmer at heart",
    "For sure",
    "Like we're living in 1984",
    "Haha",
    "Bro what are you doing",
    "You're an IBM champion right?",
    # 8 January, 2025 - 12:13am CST
    "Gotcha lol",
    "That makes sense",
    "Lionel really wants me to apply to be an IBM champion",
    "Idk why",
    "Yeah I could see that",
    "What did you work on at IBM?",
    "Sick",
    "System test is on its way to india",
    "So that part of the article has come true",
    # 8 January, 2025 - 12:47am CST
    "Yeah, I'll think about being a mod or let me know if there's anything else I can help out with!",
    "I really love that this community exists and I should give back to it besides starting fights all the time",
    "Yes!",
    "Fight me!",
    "it's really hard for me",
    "noted",
    "okay that's reassuring",
    "Okay!",
    "I'm about to pass out man. Get some good z's and enjoy the rest of your week!",
    # 8 January, 2025 - 4:20pm CST
    "Just causing shit at work",
    "Being a pariah",
    "I said I think I'm probably gonna get fired soon and it was a screenshot of my conversation with my boss",
    "Called him out for hiring  incumbents like me and the rest of his workforce",
    "My company is in \"the club\" and it took me until last night to realize that",
    "Thank you",
    # 8 January, 2025 - 4:28pm CST
    "Agreed.",
    # 8 January, 2025 - 5:12pm CST
    "I just need to learn to cause shit in the right places / ways",
    # 9 January, 2025 - 4:58am CST
    "This is why I'm starting my own ISV. Money talks.",
    "I kept the job.",
    "Idk why",
    "It doesn't  bring me joy",
    "Sabotaging my coworker and the sysplex today brought me a ton of joy.",
    "To be clear I just started cancelling a coworker's user ID over and over and then I renamed the login proc so no one could get into TSO",
    "this is why I can't be a mod",
    "I started pulling this shit at IBM too and that's when I decided it was time to call it quits",
    "Cuz I felt like I was damaging all my relationships and that made me feel sad",
    "But idk how else to get people to listen to me.",
    # 9 January, 2025 - 5:05am CST
    "Actions speak louder than words.",
    # 9 January, 2025 - 7:11am CST
    "Thanks dude",
    "Thanks dude",
    "Do something about it with me.",
    "You already did.",
    "Thank you.",
    # 9 January, 2025 - 7:35am CST
    "Emma made the wrong move.",
    "You literally told me to start fights with people.",
    # 9 January, 2025 - 7:55am CST
    "I'm not. Thanks",
    "I love you dude",
    "I've never had a mentor near my age",
    # 9 January, 2025 - 8:07am CST
    ":smile:",
    "I think it is a problem that I haven't had a mentor near my age",
    "Okay, sensei.",
    "Okay, king.",
    "It is!!",
    "So in my view, its fine.",
    "You're mentoring me on how to work with people to accomplish big tasks",
    "I'm really bad at working with people to accomplish big tasks",
    "I need a union",
    "Well, I've never been in on e. So I'm kinda clueless too.",
    "But, wouldn't you be more willing going into mainframe if you had a union behind you?",
    "I would",
    "I think it would drive outsourcing",
    "Yep",
    # 9 January, 2025 - 10:03am CST
    "think I could get emma to ban me?",
    "To make myself a pariah",
    "To drive change",
    "It's okay, I'm considered an incumbent in this industry. I am safe.",
    "I'm in \"the club\".",
    "People like me for some reason",
    "But imagine if I got banned from mainframes or something",
    "I'd take it to court",
    "Imagine if someone shot me or something idk",
    "Then maybe people would listen?",
    "sorry I know that they are",
    "Then maybe people would take action?",
    "Drastic, immediate, action.",
    "I'm done playing the long game",
    "Can't wait until z?OS 3.1 comes out I have some great cod ein there",
    "I want it",
    "I want people to see me suffer",
    "I set up a code review and got reemed at IBM for an hour by Peter Fucking Relson",
    "JUst so my peers could see what they were getting into",
    "That's the problem.",
    "People don't care.",
    "We're suffering.",
    "You know",
    "People are so afraid of making the wrong moves these days",
    "It's led to stagnation",
    # 9 January, 2025 - 10:10am CST
    "I'm so fucking sick of having to go through life taking in billions of inputs and being expected to take the best course of action all the time",
    "IT DOESN'T WORK.",
    "REVOLUTION!",
    "DISMANTLE THE ESTABLISHMENT",
    "Idk",
    "I feel like HAL9000 caught in a strange loop",
    "No, I should pick one.",
    "\"Revolutionize the IT industry\"",
    "\"Dismantle capitalism\"",
    "\"Migrate everyone off IBM Z so IBM dies\"",
    "They don't have to be",
    "But probably",
    "Probably go outside and take a walk",
    "Probably start there",
    "That's a battle I can win",
    "Touch some grass",
    "Sorry for my toxicity",
    "\"I am a product of the world I live in.\" I sent that to my dad this morning",
    "He was so proud of me for sabotaging my company's mainframe without losing my job lol",
    # 9 January, 2025 - 10:17am CST
    "I need therapy.",
    "Breaking things",
    "I was going for a while. Made me feel so shitty.",
    "Understandable",
    "Please",
    "I'm clearly burned out",
    "I know",
    "yeah",
    "i'm a catalyst",
    "it is",
    "*type",
    "misunderstanding",
    # 9 January, 2025 - 10:27am CST
    "Gotta crack a couple frog eggs if you want to make an omelette",
    "What do you think could be better?",
    "I didn't make it to those",
    "Sadly",
    "It really seemed like you were trying to get people riled up lol and I was so for it",
    "For me, it's just not a setting I feel comfortable being incendiary in I think",
    "But if some of my \"enemies\" were there it would have been easier",
    "right",
    "I appreciate it",
    "I'm trying to find the conversation I was having with Emma (my wife) while I was there",
    "Yep!!",
    "are you me",
    "that's why I left IBM",
    "well, one of many reasons",
    "i was hurting people around me (outside work) and it sucked.",
    # 9 January, 2025 - 10:34am CST
    "thanks for having the right priorities",
    # 9 January, 2025 - 10:42am CST
    "they're right in my book",
    "but yewah",
    "as always, thanks for the conversation",
    # 9 January, 2025 - 2:14pm CST
    "So idk if this is what I'm missing, but I feel like a support player / healer in a game without anyone tanking",
    "like we have plenty of people dealing damage and I can individually help people",
    "But it doesn't feel like it contributes to the greater cause",
    "So I'm trying to tank and I want people to support me",
    "But they're off DPSing and living their lives which is GREAT but I really want to beat this raid",
    "So what I'm missing is that life isn't a MOBA",
    "lol",
    "Also I love tanking in video games but not in real life. I'm a fragile snowflake.",
    "So I'm trying to tank and probably tanking my prospects to accomplish my goals in the process because it brings me a lot of inner turmoil",
    "Like I can solo support and take on small battles myself and that's what I should stick to I guess",
    # 9 January, 2025 - 2:22pm CST
    "[Showing a game you mastered for many years to someone you care about] [Ok, now press space to jump]",
    # 9 January, 2025 - 4:08pm CST
    "'Sall good asynchronous communication baby",
    "Confidence. That's what I lost. Thank you.",
    # 9 January, 2025 - 4:08pm CST
    "you're absolutely right",
    "butt there have been so many victories that I've forgotten about over the years",
    "lmao I said butt",
    "yeah",
    "everything changes so fast and it is a wild and terrifying ride",
    "but we're all in this together",
    "holy shit dude",
    "That was a good sentence",
    "The nice thing about streaming is that it's just the person streaming who is talking",
    "I think a lot of text-based communities fall apart because communicating through text inevitably leads to misunderstandings",
    "But I don't know if I feel comfortable with 4 strangers talking in an online voice chat for some reason",
    "Like what if three people gang up on someone",
    # 9 January, 2025 - 4:15pm CST
    "Why do I feel like that's more likely in a voice chat channel? I don't know, maybe because I myself don't feel comfortable in them",
    "I'd be willing to try to make this happen if you're interested. I think a lot of people might like this. It could be an experiment.",
    "I left some really scary artifacts behind at IBM",
    "Videos of me breaking don't crying during meetings",
    "Because I wanted to warn the future people in this space",
    "I just uploaded them to the team box folder",
    "Nobody has ever asked me about them",
    "Let's see what other people think about the voice chat channels.",
    # 9 January, 2025 - 4:31pm CST
    "Is this considered to be against the rules? Gaming the order of names?",
    "Purge 2025 sounds kinda scary",
  ]

  def test_iebiball(self):
    """
    Assemble, load, and execute the IEBIBALL.
    """
    print('\n'.join(self.messages))
    f = IEBIBALL(self.messages)
    f()
